# Site settings
title: Newbian Journey
header-img: img/home-bg.png
email: jpatricklogan@gmail.com
copyright_name: CaptRat
description: > # this means to ignore newlines until "baseurl:"
  Traveling into the mystical binary world
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CaptRat
learn_profile: CaptRat
email_username: jpatricklogan@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
